import Head from 'next/head';
import type { NextPage } from 'next';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>WOO HOO</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="mx-auto flex min-h-screen max-w-5xl flex-col justify-center">
        <h1 className="text-center text-9xl font-black text-fuchsia-300">
          Gonna make a sandwich brb..
        </h1>
      </main>
    </>
  );
};

export default Home;
